id: P10F80BF9
initial_creation_type: input
source_metadata:
  title: Mahāmudrā Series
  language: fr
  description: 'Lotsawa House presents the following texts on the subject of Mahāmudrā
    (phyag chen) or the ''Great Seal'':'
  volume:
    5cb47abd5eec49f9b8058592ef153d17:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      parent: Advice
    24a355d76ae34540952fca706d5d6086:
      title: Mahāmudrā Preliminaries, Main Part & Conclusion
      parent: Advice
    cf73cfe1780c407296e675f59e05eebd:
      title: 'Mahāmudrā: the Swift Way to Become a Lord of Realization'
      parent: Advice
    bbcf839ba11342a2ae4aeebe3e4982ec:
      title: The Kusāli's Instruction on the Nature of Mind
      parent: Advice
    0ac11f69dac5491bb436051c29f7da50:
      title: A Way of Settling into the Realization of Mind’s Essence
      parent: Advice
    fae1dce58a2248ebb4b83a6d0665d239:
      title: 'From the Mahāmudrā Preliminary Practices: Continuous Integration with
        Ground, Path, and Fruition'
      parent: Advice
    5276560091c6439faac64d91eea770fd:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Advice
    4be70ee98dda4bf09ca5d6ba7112cecf:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Advice
    0041b4a10eaa4d319d0bad95d1dbb385:
      title: The Mahāmudrā Practice of Stillness, Movement and Awareness
      parent: Advice
    e010035d74144e93868874ccedf7b4a2:
      title: Instructions on the Fivefold Mahāmudrā
      parent: Advice
    29665442bca24991a4d3614bfd19d3ef:
      title: Pointing Out Instruction
      parent: Advice
    42104147ed1644918968a44e4943db26:
      title: The Ganges Mahāmudrā Instructions
      parent: Advice
    c3d5258b7c944ec0a2eac2f993481fdd:
      title: Aspiration of the Mahāmudrā of Definitive Meaning
      parent: Aspiration Prayers
    5ea7c0e452e34d4f9ef8628f88ee542a:
      title: 'A Casket of Sacred Dharma: Stages of Meditation on Dependent Arising'
      parent: Commentaries
    ef7b64d0212f44f29b8414244bb18ae9:
      title: The Concise Mahāmudrā Preliminaries Arranged for Recitation
      parent: Preliminaries
    194fe8f699004907a19e59785b56e40d:
      title: 'The Excellent Path of Definitive Meaning: An Unmistaken Expression of
        the Definitive Mahāmudrā'
      parent: Songs
created_at: '2022-03-01T04:32:39.533233'
last_modified_at: '2022-03-01T04:32:39.533235'
